function Payments() {
      return (
          <section className="section payments" id="payments">
                <div className="container payment-grid">
                        <div className="payment-copy">
                                  <p className="eyebrow">Crypto Payment Gateway</p>

                                            <h2>Deposits and withdrawals built for modern investors</h2>

                                                      <p>
                                                                  Accept BTC, ETH, USDT, and BNB with automated wallet monitoring,
                                                                              secure custody, and instant settlement visibility for every
                                                                                          transfer.
                                                                                                    </p>

                                                                                                              <div className="payment-badges">
                                                                                                                          <span>BTC</span>
                                                                                                                                      <span>ETH</span>
                                                                                                                                                  <span>USDT</span>
                                                                                                                                                              <span>BNB</span>
                                                                                                                                                                        </div>

                                                                                                                                                                                  <ul className="payment-list">
                                                                                                                                                                                              <li>Multi-chain support with low-cost routing</li>
                                                                                                                                                                                                          <li>AML safeguards and wallet address verification</li>
                                                                                                                                                                                                                      <li>Real-time payment confirmations</li>
                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                <div className="payment-card">
                                                                                                                                                                                                                                                          <div className="payment-card-header">
                                                                                                                                                                                                                                                                      <h3>Quick Gateway</h3>
                                                                                                                                                                                                                                                                                  <span className="status-pill">Live</span>
                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                      <form className="payment-form">
                                                                                                                                                                                                                                                                                                                  <label htmlFor="amount">Amount</label>

                                                                                                                                                                                                                                                                                                                              <div className="amount-row">
                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                            id="amount"
                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                            defaultValue={5000}
                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                        <select>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <option>USD</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option>EUR</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option>GBP</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label htmlFor="asset">Asset</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <select id="asset">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option>BTC</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option>ETH</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option>USDT</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option>BNB</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label htmlFor="wallet">Wallet Address</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id="wallet"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="bc1q..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="btn btn-primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Initiate Payment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="payment-note">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Protected by multi-signature custody and institutional monitoring.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Payments;
