function Plans() {
      return (
          <section className="section plans" id="plans">
                <div className="container">
                        <div className="section-heading">
                                  <p className="eyebrow">Investment Plans</p>
                                            <h2>Choose a strategy that fits your ambition</h2>
                                                    </div>

                                                            <div className="card-grid">
                                                                      <article className="plan-card">
                                                                                  <h3>Conservative</h3>
                                                                                              <p className="price">
                                                                                                            6–8% <span>/ month</span>
                                                                                                                        </p>

                                                                                                                                    <ul>
                                                                                                                                                  <li>Capital preservation focus</li>
                                                                                                                                                                <li>Low-volatility allocations</li>
                                                                                                                                                                              <li>Quarterly reviews</li>
                                                                                                                                                                                          </ul>
                                                                                                                                                                                                    </article>

                                                                                                                                                                                                              <article className="plan-card featured">
                                                                                                                                                                                                                          <h3>Balanced</h3>
                                                                                                                                                                                                                                      <p className="price">
                                                                                                                                                                                                                                                    10–12% <span>/ month</span>
                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                            <ul>
                                                                                                                                                                                                                                                                                          <li>Mixed growth and protection</li>
                                                                                                                                                                                                                                                                                                        <li>Active portfolio rebalancing</li>
                                                                                                                                                                                                                                                                                                                      <li>Priority support</li>
                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                            </article>

                                                                                                                                                                                                                                                                                                                                                      <article className="plan-card">
                                                                                                                                                                                                                                                                                                                                                                  <h3>Growth</h3>
                                                                                                                                                                                                                                                                                                                                                                              <p className="price">
                                                                                                                                                                                                                                                                                                                                                                                            15%+ <span>/ month</span>
                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                    <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <li>Higher-growth allocation mix</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <li>Dynamic opportunity capture</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <li>Dedicated market insights</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Plans;
